/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "product";
  };
  userId?: string;
  userName?: string;
  rating?: number;
  comment?: string;
  createdAt?: string;
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  products?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    _key: string;
  }>;
  orderNumber?: string;
  totalPrice?: number;
  status?: "pending" | "Paid" | "delivered" | "cancelled";
  OrderDate?: string;
  clerkUserId?: string;
  email?: string;
  customerName?: string;
  phone?: string;
  address?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  topSales?: boolean;
  featuredProduct?: boolean;
  newArrival?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  price?: number;
  stock?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brands";
  };
};

export type Brands = {
  _id: string;
  _type: "brands";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Review
  | Order
  | Product
  | Brands
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: src/lib/sanityQueries.ts
// Variable: TopSales
// Query: *[_type == "product" && topSales == true]{  _id,    slug,    name,    image{      asset -> {        url      }    },    categories[]->{      _id,      slug,      name,    },    price,    stock,}
export type TopSalesResult = Array<{
  _id: string;
  slug: Slug | null;
  name: string | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    slug: Slug | null;
    name: string | null;
  }> | null;
  price: number | null;
  stock: number | null;
}>;

// Source: src/lib/sanityQueries.ts
// Variable: getNewArrivalquery
// Query: *[_type == "product" && newArrival == true]{  _id,    slug,    name,    image{      asset -> {        url      }    },    categories[]->{      _id,      slug,      name,    },    price,    stock,}
export type GetNewArrivalqueryResult = Array<{
  _id: string;
  slug: Slug | null;
  name: string | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    slug: Slug | null;
    name: string | null;
  }> | null;
  price: number | null;
  stock: number | null;
}>;

// Source: src/lib/sanityQueries.ts
// Variable: getFeaturedProductQuery
// Query: *[_type == "product" && featuredProduct == true]{  _id,    slug,    name,    image{      asset -> {        url      }    },    categories[]->{      _id,      slug,      name,    },    price,    stock,}
export type GetFeaturedProductQueryResult = Array<{
  _id: string;
  slug: Slug | null;
  name: string | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    slug: Slug | null;
    name: string | null;
  }> | null;
  price: number | null;
  stock: number | null;
}>;

// Source: src/lib/sanityQueries.ts
// Variable: TotalProductQuery
// Query: count(*[_type == "product"])
export type TotalProductQueryResult = number;

// Source: src/lib/sanityQueries.ts
// Variable: getCategory
// Query: *[_type == "category" ]{  _id,    name,      slug{        current      },          image{      asset -> {        url      }    },  }
export type GetCategoryResult = Array<{
  _id: string;
  name: string | null;
  slug: {
    current: string | null;
  } | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;

// Source: src/lib/sanityQueries.ts
// Variable: getBrandsQuery
// Query: *[_type == "brands" ]{  _id,    name,      slug{        current      },          image{      asset -> {        url      }    },  }
export type GetBrandsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: {
    current: string | null;
  } | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;

// Source: src/lib/sanityQueries.ts
// Variable: getCategoryBySlug
// Query: *[_type == "category" && slug.current == $slug] | order(name asc)[0]
export type GetCategoryBySlugResult = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
} | null;

// Source: src/lib/sanityQueries.ts
// Variable: getBrandsBySlug
// Query: *[_type == "brands" && slug.current == $slug] | order(name asc)[0]
export type GetBrandsBySlugResult = {
  _id: string;
  _type: "brands";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
} | null;

// Source: src/lib/sanityQueries.ts
// Variable: getClientOrdersQuery
// Query: *[_type == "order" && clerkUserId == $userId] | order(OrderDate desc) {    ...,    products[]{     ...,     product->    }   }
export type GetClientOrdersQueryResult = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      topSales?: boolean;
      featuredProduct?: boolean;
      newArrival?: boolean;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      description?: string;
      price?: number;
      stock?: number;
      categories?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "category";
      }>;
      brand?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "brands";
      };
    } | null;
    quantity?: number;
    _key: string;
  }> | null;
  orderNumber?: string;
  totalPrice?: number;
  status?: "cancelled" | "delivered" | "Paid" | "pending";
  OrderDate?: string;
  clerkUserId?: string;
  email?: string;
  customerName?: string;
  phone?: string;
  address?: string;
}>;

// Source: src/lib/sanityQueries.ts
// Variable: getProductsByCategorySlug
// Query: *[    _type == "product" &&    $slug in categories[]->slug.current  ] | order(_createdAt desc)
export type GetProductsByCategorySlugResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  topSales?: boolean;
  featuredProduct?: boolean;
  newArrival?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  price?: number;
  stock?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brands";
  };
}>;

// Source: src/lib/sanityQueries.ts
// Variable: getProductsByBrandSlug
// Query: *[    _type == "product" &&    $slug in brands[]->slug.current  ] | order(_createdAt desc)
export type GetProductsByBrandSlugResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  topSales?: boolean;
  featuredProduct?: boolean;
  newArrival?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  price?: number;
  stock?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brands";
  };
}>;

// Source: src/lib/sanityQueries.ts
// Variable: getProductWithReviewsQuery
// Query: *[_type == "product" && slug.current == $slug][0]{    name,    image,    "reviews": *[      _type == "review" &&      product._ref == ^._id    ] | order(createdAt desc) {      _id,      rating,      comment,      userName,      createdAt    }  }
export type GetProductWithReviewsQueryResult = {
  name: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  reviews: Array<{
    _id: string;
    rating: number | null;
    comment: string | null;
    userName: string | null;
    createdAt: string | null;
  }>;
} | null;

// Source: src/lib/sanityQueries.ts
// Variable: getReviewsWithProductQuery
// Query: *[_type == "review"]  | order(createdAt desc) {    _id,    rating,    comment,    userName,    createdAt,    product->{      _id,      name,      slug,      price,      image    }  }
export type GetReviewsWithProductQueryResult = Array<{
  _id: string;
  rating: number | null;
  comment: string | null;
  userName: string | null;
  createdAt: string | null;
  product: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    price: number | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "product" && topSales == true]{\n  _id,\n    slug,\n    name,\n    image{\n      asset -> {\n        url\n      }\n    },\n    categories[]->{\n      _id,\n      slug,\n      name,\n    },\n    price,\n    stock,\n}\n': TopSalesResult;
    '*[_type == "product" && newArrival == true]{\n  _id,\n    slug,\n    name,\n    image{\n      asset -> {\n        url\n      }\n    },\n    categories[]->{\n      _id,\n      slug,\n      name,\n    },\n    price,\n    stock,\n}\n': GetNewArrivalqueryResult;
    '*[_type == "product" && featuredProduct == true]{\n  _id,\n    slug,\n    name,\n    image{\n      asset -> {\n        url\n      }\n    },\n    categories[]->{\n      _id,\n      slug,\n      name,\n    },\n    price,\n    stock,\n}\n': GetFeaturedProductQueryResult;
    '\n  count(*[_type == "product"])\n': TotalProductQueryResult;
    '*[_type == "category" ]{\n  _id,\n    name,\n      slug{\n        current\n      },\n          image{\n      asset -> {\n        url\n      }\n    },\n  }': GetCategoryResult;
    '*[_type == "brands" ]{\n  _id,\n    name,\n      slug{\n        current\n      },\n          image{\n      asset -> {\n        url\n      }\n    },\n  }': GetBrandsQueryResult;
    '\n   *[_type == "category" && slug.current == $slug] | order(name asc)[0] \n  ': GetCategoryBySlugResult;
    '\n   *[_type == "brands" && slug.current == $slug] | order(name asc)[0] \n  ': GetBrandsBySlugResult;
    '\n   *[_type == "order" && clerkUserId == $userId] | order(OrderDate desc) {\n    ...,\n    products[]{\n     ...,\n     product->\n    }\n   }\n  ': GetClientOrdersQueryResult;
    '\n  *[\n    _type == "product" &&\n    $slug in categories[]->slug.current\n  ] | order(_createdAt desc)\n': GetProductsByCategorySlugResult;
    '\n  *[\n    _type == "product" &&\n    $slug in brands[]->slug.current\n  ] | order(_createdAt desc)\n': GetProductsByBrandSlugResult;
    '\n  *[_type == "product" && slug.current == $slug][0]{\n    name,\n    image,\n\n    "reviews": *[\n      _type == "review" &&\n      product._ref == ^._id\n    ] | order(createdAt desc) {\n      _id,\n      rating,\n      comment,\n      userName,\n      createdAt\n    }\n  }\n': GetProductWithReviewsQueryResult;
    '\n  *[_type == "review"]\n  | order(createdAt desc) {\n    _id,\n    rating,\n    comment,\n    userName,\n    createdAt,\n\n    product->{\n      _id,\n      name,\n      slug,\n      price,\n      image\n    }\n  }\n': GetReviewsWithProductQueryResult;
  }
}
